### PR TITLE
Add Ansible inventory and role for user creation

### PR DESCRIPTION
**Pull request by nbraud**

### CODE REVIEW

**Comment by equinox0815** [comment]
You know that there is already an ansible repo on git.realraum.at?

**Comment by nbraud** [comment]
@equinox0815 Neither @gebi nor I knew that.
I guess this will make some stuff easier.  ;)

Should we keep the `ansible` repo separate, or merge it with the `noc` repo?
I would be in favor of merging, since it means we can keep (and modify) the documentation and ansible stuff together.

**Comment by equinox0815** [comment]
I'm in favor of talking at least once about what we are going to put where. We are very good at starting new repos only to not use them after 1 week of work.
It would be great if when repos are created we could get ourselves to send out at least an eMail about why we did that and what we intended to do with it. See #3

btw. gebi knows that i started a ansible repo for realaum - we talked about that several months ago

**Comment by nbraud** [comment]
Closing, and I will extract the user management stuff to a new branch.

**Pull request closed without merging**
